#!/bin/sh

set -e

echo "Running zig fmt..."
zig fmt --check src

echo "Running zsort check..."
zsort check src

echo "Running zig build test..."
zig build test  --summary all

echo "All checks passed successfully!"
